packages:
  - apps/*
  - packages/*
  - server
  - e2e

catalog:
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
  '@vitest/coverage-v8': 4.0.18
  next: ^16.1.6
  react: ^19.2.3
  react-dom: ^19.1.0
  typescript: ^5.9.2
  vitest: ^4.0.18

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

nodeLinker: hoisted

onlyBuiltDependencies:
  - cpu-features
  - ssh2
